# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20171013_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
