# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_url',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='domain',
            name='encode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain_ip',
            name='encode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Domain'),
        ),
    ]
