# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20171016_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='respone_way',
            field=models.CharField(choices=[('Http', 'Http'), ('Https', 'Https')], max_length=5),
        ),
    ]
